name: Workflow Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore*'
  pull_request:
    branches-ignore:
      - 'ga-ignore*'

env:
  MIRROR_URL: git@github.com:EpitechPGEPromo2029/B-DOP-200-COT-2-1-chocolatine-horus.kpodohoun.git
  EXECUTABLES: mysh

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name:
      - uses: action/chaeckout@v4
      - name:
       run: check.sh $(pwd) $(pwd)